/**
 * RAG Types - Shared
 *
 * Shared types/interfaces for RAG nodes and relationships, based on ai-server/core/types.
 * Used for backend <-> ai-server <-> shared integration.
 *
 * @module shared/types/ragTypes
 */

export type RAGNodeType =
    | 'character'
    | 'location'
    | 'plot_point'
    | 'event'
    | 'lore'
    | 'book'
    | 'chapter'
    | 'scene'
    | 'dialogue'
    | 'universe'
    | 'species'
    | 'technology'
    | 'organization'
    | 'ai-model'
    | 'ai-server'
    | 'model-performance'
    | 'source_chunk'
    | 'code_snippet'
    | 'code_file'
    | 'test_case'
    | 'api_endpoint'
    | 'requirement'
    | 'task'
    | 'comment'
    | 'issue'
    | 'commit'
    | 'reference'
    | 'shared_memory'
    | 'character_memory'
    | 'custom';

export interface RAGNodeContent {
    description: string;
    attributes?: Record<string, any>;
    structured?: any;
    fullText?: string;
}

export interface RAGNodeSummaries {
    brief: string;
    medium: string;
    detailed: string;
    autoGenerated?: boolean;
    lastUpdated?: Date;
}

export interface RAGNodeMetadata {
    universeId: string;
    sessionId?: string;
    ownerId: string;
    sensitivity: 'public' | 'private' | 'sensitive' | 'restricted';
    tags: string[];
    categories?: string[];
    pluginType?: string;
    authorId?: string;
    collaborators?: string[];
    versionHash?: string;
    sourcePlugin?: string;
    version: number;
    importance?: number;
    bookId?: string;
    chapterId?: string;
    mood?: string;
    theme?: string;
    timelineMarkers?: string[];
}

export interface RAGNodePrivacy {
    encrypted: boolean;
    encryptionLevel?: 'basic' | 'sensitive' | 'restricted';
    keyPath?: string;
    accessList?: string[];
    shareable: boolean;
    level?: string;
    encryptedFields?: string[];
    keyHierarchy?: string;
}

export interface RAGTemporalData {
    startDate?: Date | string;
    endDate?: Date | string;
    universeTime?: string;
    sequence?: number;
    ongoing?: boolean;
    position?: number;
    stardateEquivalent?: number;
    relations?: string[];
}

export interface RAGTimestamps {
    created: Date;
    modified: Date;
    lastAccessed?: Date;
    contentHash?: string;
}

export interface RAGNode {
    id: string;
    type: RAGNodeType;
    title: string;
    content: RAGNodeContent;
    summaries: RAGNodeSummaries;
    embeddings: number[];
    metadata: RAGNodeMetadata;
    privacy: RAGNodePrivacy;
    temporal?: RAGTemporalData;
    pluginData?: Record<string, any>;
    timestamps: RAGTimestamps;
    active: boolean;
}

export type RAGRelationshipType =
    | 'semantic'
    | 'causal'
    | 'temporal'
    | 'hierarchical'
    | 'character_interaction'
    | 'location_contains'
    | 'plot_dependency'
    | 'reference'
    | 'spoken_by'
    | 'addressed_to'
    | 'conflict'
    | 'alliance'
    | 'implements'
    | 'calls'
    | 'tests'
    | 'documents'
    | 'fixes'
    | 'relates_to'
    | 'depends_on'
    | 'duplicate_of'
    | 'cross_chunk_link'
    | 'custom';

export interface RAGRelationshipMetadata {
    description?: string;
    universeId: string;
    sourcePlugin?: string;
    attributes?: Record<string, any>;
    evidence?: string[];
    pluginType?: string;
    pluginData?: Record<string, any>;
    authorId?: string;
    versionHash?: string;
    privacy?: RAGNodePrivacy;
    collaborators?: string[];
}

export interface RAGRelationshipTemporal {
    startDate?: Date | string;
    endDate?: Date | string;
    active: boolean;
    universeTime?: string;
    scope?: string;
    validFrom?: string | Date;
    validUntil?: string | Date;
    context?: string[];
}

export interface RAGRelationshipPrivacy {
    encrypted: boolean;
    encryptionLevel?: 'basic' | 'sensitive' | 'restricted';
    visibility: 'public' | 'private' | 'restricted';
    accessList?: string[];
}

export interface RAGRelationship {
    id: string;
    fromNodeId: string;
    toNodeId: string;
    type: RAGRelationshipType;
    weight: number;
    metadata: RAGRelationshipMetadata;
    temporal?: RAGRelationshipTemporal;
    privacy: RAGRelationshipPrivacy;
    timestamps: RAGTimestamps;
}
