// --- Universe/Book/Chapter/Character API ---
export interface Universe {
    id: string;
    title: string;
    type: 'universe';
    metadata?: Record<string, unknown>;
}

export interface Book {
    id: string;
    universeId: string;
    title: string;
    type: 'book';
    metadata?: Record<string, unknown>;
}

export interface Chapter {
    id: string;
    bookId: string;
    title: string;
    type: 'chapter';
    metadata?: Record<string, unknown>;
}

export interface Character {
    id: string;
    universeId?: string;
    bookId?: string;
    chapterId?: string;
    name: string;
    type: 'character';
    aliases?: string[];
    metadata?: Record<string, unknown>;
}
// ...existing code...
// ...existing code...
// ...existing code...
/**
 * RAG Service for AI Server Web UI
 * 
 * Provides a client interface for interacting with RAG endpoints
 */

export interface RAGNode {
    id: string;
    type?: string;
    nodeType?: string; // Alternative field name from API
    title?: string;
    content?: {
        description: string;
        attributes?: Record<string, any>;
        structured?: any;
        fullText?: string;
    } | string; // Can be string or object
    summaries?: {
        brief: string;
        medium: string;
        detailed: string;
        autoGenerated?: boolean;
        lastUpdated?: Date;
    };
    embeddings?: number[];
    metadata?: {
        universeId: string;
        ownerId: string;
        sensitivity: 'public' | 'private' | 'sensitive' | 'restricted';
        tags: string[];
        sourcePlugin?: string;
        version: number;
        importance?: number;
        bookId?: string;
        chapterId?: string;
    };
    // Direct fields that might come from API
    universeId?: string;
    bookId?: string;
    chapterId?: string;
    tags?: string[];
    properties?: {
        name?: string;
        description?: string;
        genre?: string;
        timeFrame?: string;
        themes?: string[];
        [key: string]: any;
    };
    privacy?: {
        encrypted: boolean;
        encryptionLevel?: 'basic' | 'sensitive' | 'restricted';
        keyPath?: string;
        accessList?: string[];
        shareable: boolean;
    };
    temporal?: {
        startDate?: Date | string;
        endDate?: Date | string;
        universeTime?: string;
        sequence?: number;
        ongoing?: boolean;
    };
    pluginData?: Record<string, any>;
    timestamps?: {
        created: Date | string;
        modified: Date | string;
        lastAccessed?: Date | string;
        contentHash?: string;
    };
    // MongoDB fields that might be present
    _id?: string;
    nodeId?: string;
}

export interface RAGRelationship {
    id: string;
    sourceNodeId: string;
    targetNodeId: string;
    type: string;
    properties: {
        strength: number;
        description?: string;
    };
    metadata: {
        universeId: string;
        title: string;
        tags?: string[];
        sensitivity?: 'low' | 'medium' | 'high';
    };
}

export interface RAGSearchResult {
    nodes: Array<{
        node: RAGNode;
        score: number;
        highlights: string[];
        matchReason: string;
    }>;
    totalCount: number;
    metadata: {
        searchTime: number;
        mode: string;
        cached: boolean;
    };
}

const API_KEY = import.meta.env.VITE_RAG_API_KEY;

function withAuth(headers: HeadersInit = {}): HeadersInit {
    if (API_KEY) {
        return { ...headers, Authorization: `Bearer ${API_KEY}` };
    }
    return headers;
}

export class RAGService {
    /**
     * Upload a canonical book/chapter file (for file-backed ingestion)
     * Returns version info and metadata
     */
    async uploadCanonicalFile(formData: FormData): Promise<{ versions: any[] }> {
        const response = await fetch(`${this.baseUrl}/api/rag/files/upload`, {
            method: 'POST',
            body: formData,
            headers: withAuth(),
        });
        if (!response.ok) {
            throw new Error(`Failed to upload file: ${response.statusText}`);
        }
        return response.json();
    }

    /**
     * Get a diff preview for a file version (added/removed/changed chunks)
     */
    async getFileDiffPreview(versionId: string): Promise<any> {
        const response = await fetch(`${this.baseUrl}/api/rag/files/diff-preview/${versionId}`, {
            headers: withAuth(),
        });
        if (!response.ok) {
            throw new Error(`Failed to get diff preview: ${response.statusText}`);
        }
        return response.json();
    }
    private baseUrl: string;


    constructor(baseUrl: string = 'http://localhost:5100') {
        this.baseUrl = baseUrl;
    }

    // --- Universes ---
    public getUniverses(): Promise<Universe[]> {
        return fetch(`${this.baseUrl}/api/universes`, { headers: withAuth() })
            .then(r => { if (!r.ok) throw new Error('Failed to fetch universes'); return r.json(); });
    }

    // --- Books ---
    public getBooks(universeId: string): Promise<Book[]> {
        return fetch(`${this.baseUrl}/api/books?universeId=${encodeURIComponent(universeId)}`, { headers: withAuth() })
            .then(r => { if (!r.ok) throw new Error('Failed to fetch books'); return r.json(); });
    }

    // --- Chapters ---
    public getChapters(bookId: string): Promise<Chapter[]> {
        return fetch(`${this.baseUrl}/api/chapters?bookId=${encodeURIComponent(bookId)}`, { headers: withAuth() })
            .then(r => { if (!r.ok) throw new Error('Failed to fetch chapters'); return r.json(); });
    }

    // --- Characters ---
    public getCharacters(params: { universeId?: string; bookId?: string; chapterId?: string } = {}): Promise<Character[]> {
        const search = new URLSearchParams();
        if (params.universeId) search.append('universeId', params.universeId);
        if (params.bookId) search.append('bookId', params.bookId);
        if (params.chapterId) search.append('chapterId', params.chapterId);
        return fetch(`${this.baseUrl}/api/characters?${search.toString()}`, { headers: withAuth() })
            .then(r => { if (!r.ok) throw new Error('Failed to fetch characters'); return r.json(); });
    }

    /**
     * Health check for RAG system
     */
    async healthCheck(): Promise<{ healthy: boolean; details?: any }> {
        const response = await fetch(`${this.baseUrl}/api/rag/health`, {
            headers: withAuth(),
        });
        if (!response.ok) {
            throw new Error(`RAG health check failed: ${response.statusText}`);
        }
        return response.json();
    }

    /**
     * Create a new RAG node
     */
    async createNode(nodeData: Omit<RAGNode, 'id' | 'timestamps'>): Promise<RAGNode> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes`, {
            method: 'POST',
            headers: withAuth({ 'Content-Type': 'application/json' }),
            body: JSON.stringify(nodeData),
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Failed to create node: ${response.statusText} - ${errorText}`);
        }

        return response.json();
    }

    /**
     * Get a RAG node by ID
     */
    async getNode(nodeId: string): Promise<RAGNode | null> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes/${nodeId}`, {
            headers: withAuth(),
        });

        if (response.status === 404) {
            return null;
        }

        if (!response.ok) {
            throw new Error(`Failed to get node: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Update a RAG node
     */
    async updateNode(nodeId: string, updates: Partial<RAGNode>): Promise<RAGNode> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes/${nodeId}`, {
            method: 'PUT',
            headers: withAuth({ 'Content-Type': 'application/json' }),
            body: JSON.stringify(updates),
        });

        if (!response.ok) {
            throw new Error(`Failed to update node: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Delete a RAG node
     */
    async deleteNode(nodeId: string): Promise<void> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes/${nodeId}`, {
            method: 'DELETE',
            headers: withAuth(),
        });

        if (!response.ok) {
            throw new Error(`Failed to delete node: ${response.statusText}`);
        }
    }

    /**
     * Search RAG nodes (GET endpoint)
     */
    async searchNodes(
        query: string,
        options: {
            universeId?: string;
            limit?: number;
            nodeType?: string;
        } = {}
    ): Promise<RAGSearchResult> {
        const params = new URLSearchParams();
        params.append('query', query);

        if (options.universeId) {
            params.append('universeId', options.universeId);
        }

        if (options.limit) {
            params.append('limit', options.limit.toString());
        }

        if (options.nodeType) {
            params.append('nodeType', options.nodeType);
        }

        const response = await fetch(`${this.baseUrl}/api/rag/search?${params}`, {
            headers: withAuth(),
        });

        if (!response.ok) {
            throw new Error(`Failed to search nodes: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Get all nodes (for development/testing)
     */
    async getAllNodes(limit: number = 50): Promise<RAGNode[]> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes?limit=${limit}`, {
            headers: withAuth(),
        });

        if (!response.ok) {
            throw new Error(`Failed to get all nodes: ${response.statusText}`);
        }

        const result = await response.json();
        // The API returns nodes directly as an array, not wrapped in an object
        return Array.isArray(result) ? result : result.nodes || [];
    }

    /**
     * Create a new RAG relationship
     */
    async createRelationship(relationshipData: Omit<RAGRelationship, 'id'>): Promise<RAGRelationship> {
        const response = await fetch(`${this.baseUrl}/api/rag/relationships`, {
            method: 'POST',
            headers: withAuth({ 'Content-Type': 'application/json' }),
            body: JSON.stringify(relationshipData),
        });

        if (!response.ok) {
            throw new Error(`Failed to create relationship: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Get system statistics
     */
    async getStats(): Promise<any> {
        const response = await fetch(`${this.baseUrl}/api/rag/stats`, {
            headers: withAuth(),
        });

        if (!response.ok) {
            throw new Error(`Failed to get stats: ${response.statusText}`);
        }

        return response.json();
    }
}

// Extend RAGService prototype with file storage methods
export const ragService = new RAGService();
