/**
 * RAG Service for AI Server Web UI
 * 
 * Provides a client interface for interacting with RAG endpoints
 */

export interface RAGNode {
    id: string;
    type?: string;
    nodeType?: string; // Alternative field name from API
    title?: string;
    content?: {
        description: string;
        attributes?: Record<string, any>;
        structured?: any;
        fullText?: string;
    } | string; // Can be string or object
    summaries?: {
        brief: string;
        medium: string;
        detailed: string;
        autoGenerated?: boolean;
        lastUpdated?: Date;
    };
    embeddings?: number[];
    metadata?: {
        universeId: string;
        ownerId: string;
        sensitivity: 'public' | 'private' | 'sensitive' | 'restricted';
        tags: string[];
        sourcePlugin?: string;
        version: number;
        importance?: number;
    };
    // Direct fields that might come from API
    universeId?: string;
    tags?: string[];
    properties?: {
        name?: string;
        description?: string;
        genre?: string;
        timeFrame?: string;
        themes?: string[];
        [key: string]: any;
    };
    privacy?: {
        encrypted: boolean;
        encryptionLevel?: 'basic' | 'sensitive' | 'restricted';
        keyPath?: string;
        accessList?: string[];
        shareable: boolean;
    };
    temporal?: {
        startDate?: Date | string;
        endDate?: Date | string;
        universeTime?: string;
        sequence?: number;
        ongoing?: boolean;
    };
    pluginData?: Record<string, any>;
    timestamps?: {
        created: Date | string;
        modified: Date | string;
        lastAccessed?: Date | string;
        contentHash?: string;
    };
    // MongoDB fields that might be present
    _id?: string;
    nodeId?: string;
}

export interface RAGRelationship {
    id: string;
    sourceNodeId: string;
    targetNodeId: string;
    type: string;
    properties: {
        strength: number;
        description?: string;
    };
    metadata: {
        universeId: string;
        title: string;
        tags?: string[];
        sensitivity?: 'low' | 'medium' | 'high';
    };
}

export interface RAGSearchResult {
    nodes: Array<{
        node: RAGNode;
        score: number;
        highlights: string[];
        matchReason: string;
    }>;
    totalCount: number;
    metadata: {
        searchTime: number;
        mode: string;
        cached: boolean;
    };
}

export class RAGService {
    private baseUrl: string;

    constructor(baseUrl: string = 'http://localhost:5100') {
        this.baseUrl = baseUrl;
    }

    /**
     * Health check for RAG system
     */
    async healthCheck(): Promise<{ healthy: boolean; details?: any }> {
        const response = await fetch(`${this.baseUrl}/api/rag/health`);
        if (!response.ok) {
            throw new Error(`RAG health check failed: ${response.statusText}`);
        }
        return response.json();
    }

    /**
     * Create a new RAG node
     */
    async createNode(nodeData: Omit<RAGNode, 'id' | 'timestamps'>): Promise<RAGNode> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(nodeData),
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Failed to create node: ${response.statusText} - ${errorText}`);
        }

        return response.json();
    }

    /**
     * Get a RAG node by ID
     */
    async getNode(nodeId: string): Promise<RAGNode | null> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes/${nodeId}`);

        if (response.status === 404) {
            return null;
        }

        if (!response.ok) {
            throw new Error(`Failed to get node: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Update a RAG node
     */
    async updateNode(nodeId: string, updates: Partial<RAGNode>): Promise<RAGNode> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes/${nodeId}`, {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(updates),
        });

        if (!response.ok) {
            throw new Error(`Failed to update node: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Delete a RAG node
     */
    async deleteNode(nodeId: string): Promise<void> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes/${nodeId}`, {
            method: 'DELETE',
        });

        if (!response.ok) {
            throw new Error(`Failed to delete node: ${response.statusText}`);
        }
    }

    /**
     * Search RAG nodes (GET endpoint)
     */
    async searchNodes(
        query: string,
        options: {
            universeId?: string;
            limit?: number;
            nodeType?: string;
        } = {}
    ): Promise<RAGSearchResult> {
        const params = new URLSearchParams();
        params.append('query', query);

        if (options.universeId) {
            params.append('universeId', options.universeId);
        }

        if (options.limit) {
            params.append('limit', options.limit.toString());
        }

        if (options.nodeType) {
            params.append('nodeType', options.nodeType);
        }

        const response = await fetch(`${this.baseUrl}/api/rag/search?${params}`);

        if (!response.ok) {
            throw new Error(`Failed to search nodes: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Get all nodes (for development/testing)
     */
    async getAllNodes(limit: number = 50): Promise<RAGNode[]> {
        const response = await fetch(`${this.baseUrl}/api/rag/nodes?limit=${limit}`);

        if (!response.ok) {
            throw new Error(`Failed to get all nodes: ${response.statusText}`);
        }

        const result = await response.json();
        // The API returns nodes directly as an array, not wrapped in an object
        return Array.isArray(result) ? result : result.nodes || [];
    }

    /**
     * Create a new RAG relationship
     */
    async createRelationship(relationshipData: Omit<RAGRelationship, 'id'>): Promise<RAGRelationship> {
        const response = await fetch(`${this.baseUrl}/api/rag/relationships`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(relationshipData),
        });

        if (!response.ok) {
            throw new Error(`Failed to create relationship: ${response.statusText}`);
        }

        return response.json();
    }

    /**
     * Get system statistics
     */
    async getStats(): Promise<any> {
        const response = await fetch(`${this.baseUrl}/api/rag/stats`);

        if (!response.ok) {
            throw new Error(`Failed to get stats: ${response.statusText}`);
        }

        return response.json();
    }
}

// Export singleton instance
export const ragService = new RAGService();
