/**
 * RAG Node Implementation
 * 
 * Core implementation of RAG nodes with built-in privacy, encryption,
 * and multi-layer summarization capabilities.
 */

import { randomUUID } from 'crypto';
import {
    RAGNode,
    RAGNodeType,
    RAGNodeContent,
    RAGNodeMetadata,
    RAGNodePrivacy,
    RAGNodeSummaries,
    RAGTemporalData,
    RAGTimestamps
} from './types.js';

/**
 * RAG Node creation parameters
 */
export interface CreateRAGNodeParams {
    type: RAGNodeType;
    title: string;
    content: RAGNodeContent;
    metadata: Omit<RAGNodeMetadata, 'version'>;
    privacy?: Partial<RAGNodePrivacy>;
    temporal?: RAGTemporalData;
    pluginData?: Record<string, any>;
    embeddings?: number[];
}

/**
 * RAG Node factory and utility functions
 */
export class RAGNodeFactory {
    /**
     * Create a new RAG node with proper defaults
     */
    static create(params: CreateRAGNodeParams): RAGNode {
        const now = new Date();

        // Generate initial summaries from content
        const summaries = this.generateInitialSummaries(params.content, params.type);

        const node: RAGNode = {
            id: randomUUID(),
            type: params.type,
            title: params.title,
            content: params.content,
            summaries,
            embeddings: params.embeddings || [],
            metadata: {
                ...params.metadata,
                version: 1
            },
            privacy: {
                encrypted: false,
                shareable: true,
                ...params.privacy
            },
            temporal: params.temporal,
            pluginData: params.pluginData,
            timestamps: {
                created: now,
                modified: now,
                contentHash: this.generateContentHash(params.content)
            },
            active: true // Hybrid orchestrator: all new nodes are active by default
        };

        return node;
    }

    /**
     * Update an existing RAG node
     */
    static update(
        existingNode: RAGNode,
        updates: Partial<Omit<RAGNode, 'id' | 'timestamps' | 'metadata'>> & {
            metadata?: Partial<RAGNodeMetadata>;
        }
    ): RAGNode {
        const now = new Date();
        const contentChanged = updates.content &&
            this.generateContentHash(updates.content) !== existingNode.timestamps.contentHash;

        // Regenerate summaries if content changed
        let summaries = existingNode.summaries;
        if (contentChanged && updates.content) {
            summaries = this.generateInitialSummaries(updates.content, updates.type || existingNode.type);
        }

        return {
            ...existingNode,
            ...updates,
            summaries: updates.summaries || summaries,
            metadata: {
                ...existingNode.metadata,
                ...updates.metadata,
                version: contentChanged ? existingNode.metadata.version + 1 : existingNode.metadata.version
            },
            timestamps: {
                ...existingNode.timestamps,
                modified: now,
                contentHash: contentChanged && updates.content ?
                    this.generateContentHash(updates.content) :
                    existingNode.timestamps.contentHash
            }
        };
    }

    /**
     * Generate initial summaries from content
     */
    private static generateInitialSummaries(content: RAGNodeContent, type: RAGNodeType): RAGNodeSummaries {
        const description = content.description || '';
        const words = description.split(' ');

        // Simple text truncation for initial implementation
        // TODO: Replace with AI-powered summarization
        const brief = words.slice(0, 10).join(' ') + (words.length > 10 ? '...' : '');
        const medium = words.slice(0, 25).join(' ') + (words.length > 25 ? '...' : '');
        const detailed = words.slice(0, 50).join(' ') + (words.length > 50 ? '...' : '');

        return {
            brief: brief || `${type}: ${content.description?.substring(0, 50) || 'No description'}`,
            medium: medium || content.description?.substring(0, 150) || 'No description',
            detailed: detailed || content.description?.substring(0, 300) || 'No description',
            autoGenerated: true,
            lastUpdated: new Date()
        };
    }

    /**
     * Generate content hash for change detection
     */
    private static generateContentHash(content: RAGNodeContent): string {
        const crypto = require('crypto');
        const contentString = JSON.stringify(content, Object.keys(content).sort());
        return crypto.createHash('sha256').update(contentString).digest('hex');
    }

    /**
     * Validate RAG node structure
     */
    static validate(node: RAGNode): { valid: boolean; errors: string[] } {
        const errors: string[] = [];

        if (!node.id) errors.push('Node must have an ID');
        if (!node.type) errors.push('Node must have a type');
        if (!node.title) errors.push('Node must have a title');
        if (!node.content) errors.push('Node must have content');
        if (!node.metadata) errors.push('Node must have metadata');
        if (!node.metadata.universeId) errors.push('Node must have a universe ID');
        if (!node.metadata.ownerId) errors.push('Node must have an owner ID');
        if (!node.timestamps) errors.push('Node must have timestamps');

        // Validate privacy settings
        if (node.privacy.encrypted && !node.privacy.encryptionLevel) {
            errors.push('Encrypted nodes must specify encryption level');
        }

        // Validate temporal data
        if (node.temporal) {
            if (node.temporal.startDate && node.temporal.endDate) {
                const start = new Date(node.temporal.startDate);
                const end = new Date(node.temporal.endDate);
                if (start > end) {
                    errors.push('Temporal start date cannot be after end date');
                }
            }
        }

        return {
            valid: errors.length === 0,
            errors
        };
    }

    /**
     * Clone a RAG node with new ID
     */
    static clone(node: RAGNode, overrides?: Partial<CreateRAGNodeParams>): RAGNode {
        const cloneParams: CreateRAGNodeParams = {
            type: node.type,
            title: overrides?.title || `Copy of ${node.title}`,
            content: { ...node.content, ...overrides?.content },
            metadata: {
                universeId: node.metadata.universeId,
                ownerId: node.metadata.ownerId,
                sensitivity: node.metadata.sensitivity,
                tags: [...node.metadata.tags],
                sourcePlugin: node.metadata.sourcePlugin,
                importance: node.metadata.importance,
                ...overrides?.metadata
            },
            privacy: { ...node.privacy, ...overrides?.privacy },
            temporal: node.temporal ? { ...node.temporal, ...overrides?.temporal } : overrides?.temporal,
            pluginData: { ...node.pluginData, ...overrides?.pluginData },
            embeddings: overrides?.embeddings || [...node.embeddings]
        };

        return this.create(cloneParams);
    }

    /**
     * Get appropriate summary for context layer
     */
    static getSummaryForLayer(node: RAGNode, layer: number): string {
        switch (layer) {
            case 0: // Focal point - full content
                return node.content.description;
            case 1: // Direct connections - detailed summary
                return node.summaries.detailed;
            case 2: // Secondary connections - medium summary
                return node.summaries.medium;
            default: // Distant context - brief summary
                return node.summaries.brief;
        }
    }

    /**
     * Check if user has access to this node
     */
    static hasAccess(node: RAGNode, userId: string, accessLevel: 'read' | 'write' = 'read'): boolean {
        // Owner always has access
        if (node.metadata.ownerId === userId) {
            return true;
        }

        // Check if node is shareable
        if (!node.privacy.shareable) {
            return false;
        }

        // Check access list if present
        if (node.privacy.accessList && node.privacy.accessList.length > 0) {
            return node.privacy.accessList.includes(userId);
        }

        // Default access based on sensitivity
        switch (node.metadata.sensitivity) {
            case 'public':
                return true;
            case 'private':
                return false;
            case 'sensitive':
            case 'restricted':
                return false;
            default:
                return false;
        }
    }

    /**
     * Prepare node for serialization (remove sensitive data if needed)
     */
    static serialize(node: RAGNode, userId: string, includePrivate: boolean = false): Partial<RAGNode> {
        if (!this.hasAccess(node, userId)) {
            return {
                id: node.id,
                type: node.type,
                title: 'Access Denied',
                content: { description: 'You do not have access to view this content.' },
                summaries: {
                    brief: 'Access Denied',
                    medium: 'Access Denied',
                    detailed: 'Access Denied'
                },
                embeddings: [],
                metadata: {
                    universeId: node.metadata.universeId,
                    ownerId: '[Hidden]',
                    sensitivity: node.metadata.sensitivity,
                    tags: [],
                    version: 0
                },
                privacy: {
                    encrypted: node.privacy.encrypted,
                    shareable: false
                },
                timestamps: {
                    created: node.timestamps.created,
                    modified: node.timestamps.modified
                }
            };
        }

        // Return full node if user has access
        if (includePrivate) {
            return node;
        }

        // Remove sensitive internal data
        const serialized = { ...node };
        delete serialized.pluginData;
        if (serialized.privacy.accessList) {
            serialized.privacy = { ...serialized.privacy, accessList: undefined };
        }

        return serialized;
    }
}
