/**
 * RAG System Core Types and Interfaces
 * 
 * Defines the fundamental data structures for the RAG-first knowledge graph system.
 * This is designed to support Obsidian-style knowledge management with multi-layer
 * context, temporal relationships, and plugin-extensible content types.
 */

/**
 * Core RAG node interface supporting multiple content types
 */
export interface RAGNode {
    /** Unique identifier for the node */
    id: string;

    /** Content type (characters, locations, plot_points, events, lore, books, chapters, scenes, dialogue, etc.) */
    type: RAGNodeType;

    /** Display title/name of the node */
    title: string;

    /** Full content data - varies by node type */
    content: RAGNodeContent;

    /** Summary content for different context layers */
    summaries: RAGNodeSummaries;

    /** Vector embeddings for semantic search */
    embeddings: number[];

    /** Metadata and classification */
    metadata: RAGNodeMetadata;

    /** Encryption and privacy settings */
    privacy: RAGNodePrivacy;

    /** Temporal information for timeline features */
    temporal?: RAGTemporalData;

    /** Plugin-specific data */
    pluginData?: Record<string, any>;

    /** Creation and modification timestamps */
    timestamps: RAGTimestamps;
}

/**
 * Node types supported by the RAG system
 */
export type RAGNodeType =
    | 'character'
    | 'location'
    | 'plot_point'
    | 'event'
    | 'lore'
    | 'book'
    | 'chapter'
    | 'scene'
    | 'dialogue'
    | 'universe'
    | 'species'
    | 'technology'
    | 'organization'
    | 'ai-model'          // AI language models
    | 'ai-server'         // AI inference servers
    | 'model-performance' // Performance data nodes
    | 'custom';           // For plugin-defined types

/**
 * Content structure varies by node type
 */
export interface RAGNodeContent {
    /** Main descriptive content */
    description: string;

    /** Key facts and attributes */
    attributes?: Record<string, any>;

    /** Structured data specific to node type */
    structured?: any;

    /** Raw text content for full-text search */
    fullText?: string;
}

/**
 * Multi-layer summaries for context assembly
 */
export interface RAGNodeSummaries {
    /** Brief one-line summary for distant context (Layer 3+) */
    brief: string;

    /** Medium-detail summary for secondary connections (Layer 2) */
    medium: string;

    /** Detailed summary for direct connections (Layer 1) */
    detailed: string;

    /** Auto-generated summaries updated when content changes */
    autoGenerated?: boolean;

    /** Last update timestamp for summaries */
    lastUpdated?: Date;
}

/**
 * Metadata and classification information
 */
export interface RAGNodeMetadata {
    /** Universe this node belongs to */
    universeId: string;

    /** User who created/owns this node */
    ownerId: string;

    /** Content sensitivity classification */
    sensitivity: 'public' | 'private' | 'sensitive' | 'restricted';

    /** Tags for categorization and search */
    tags: string[];

    /** Plugin that contributed this node type */
    sourcePlugin?: string;

    /** Version number for content tracking */
    version: number;

    /** Importance/relevance scoring */
    importance?: number;
}

/**
 * Privacy and encryption settings
 */
export interface RAGNodePrivacy {
    /** Whether content is encrypted */
    encrypted: boolean;

    /** Encryption level if encrypted */
    encryptionLevel?: 'basic' | 'sensitive' | 'restricted';

    /** Key derivation path for hierarchical encryption */
    keyPath?: string;

    /** Access control list */
    accessList?: string[];

    /** Whether this can be shared in collaborative contexts */
    shareable: boolean;
}

/**
 * Temporal data for timeline features
 */
export interface RAGTemporalData {
    /** Start date/time for events */
    startDate?: Date | string;

    /** End date/time for events */
    endDate?: Date | string;

    /** Universe-specific time format (stardate, BBY/ABY, etc.) */
    universeTime?: string;

    /** Timeline order/sequence number */
    sequence?: number;

    /** Whether this is a recurring or ongoing element */
    ongoing?: boolean;
}

/**
 * Creation and modification timestamps
 */
export interface RAGTimestamps {
    created: Date;
    modified: Date;
    lastAccessed?: Date;
    contentHash?: string; // Hash of content for change detection
}

/**
 * Relationship between RAG nodes
 */
export interface RAGRelationship {
    /** Unique identifier for the relationship */
    id: string;

    /** Source node ID */
    fromNodeId: string;

    /** Target node ID */
    toNodeId: string;

    /** Type of relationship */
    type: RAGRelationshipType;

    /** Relationship strength/weight (0-1) */
    weight: number;

    /** Additional relationship metadata */
    metadata: RAGRelationshipMetadata;

    /** Temporal aspects of the relationship */
    temporal?: RAGRelationshipTemporal;

    /** Privacy settings for the relationship */
    privacy: RAGRelationshipPrivacy;

    /** Creation and modification timestamps */
    timestamps: RAGTimestamps;
}

/**
 * Types of relationships between nodes
 */
export type RAGRelationshipType =
    | 'semantic' // General semantic connection
    | 'causal' // Cause and effect
    | 'temporal' // Time-based connection
    | 'hierarchical' // Parent-child relationship
    | 'character_interaction' // Characters interacting
    | 'location_contains' // Location contains another element
    | 'plot_dependency' // Plot point depends on another
    | 'reference' // References or mentions
    | 'conflict' // Opposing or conflicting elements
    | 'alliance' // Cooperative relationship
    | 'custom'; // Plugin-defined relationship types

/**
 * Metadata for relationships
 */
export interface RAGRelationshipMetadata {
    /** Description of the relationship */
    description?: string;

    /** Universe this relationship exists in */
    universeId: string;

    /** Plugin that defined this relationship type */
    sourcePlugin?: string;

    /** Custom attributes */
    attributes?: Record<string, any>;

    /** Evidence or references supporting this relationship */
    evidence?: string[];
}

/**
 * Temporal aspects of relationships
 */
export interface RAGRelationshipTemporal {
    /** When the relationship began */
    startDate?: Date | string;

    /** When the relationship ended */
    endDate?: Date | string;

    /** Whether the relationship is currently active */
    active: boolean;

    /** Universe-specific time format */
    universeTime?: string;
}

/**
 * Privacy settings for relationships
 */
export interface RAGRelationshipPrivacy {
    /** Whether relationship is encrypted */
    encrypted: boolean;

    /** Encryption level */
    encryptionLevel?: 'basic' | 'sensitive' | 'restricted';

    /** Who can see this relationship */
    visibility: 'public' | 'private' | 'restricted';

    /** Access control list */
    accessList?: string[];
}

/**
 * Context assembly request parameters
 */
export interface RAGContextRequest {
    /** Focal node ID */
    focalNodeId: string;

    /** Maximum context distance (layers) */
    maxDistance: number;

    /** Maximum total tokens to use */
    maxTokens: number;

    /** Priority filters */
    filters?: RAGContextFilters;

    /** Context assembly strategy */
    strategy?: RAGContextStrategy;

    /** User making the request (for privacy) */
    userId: string;
}

/**
 * Filters for context assembly
 */
export interface RAGContextFilters {
    /** Include only specific node types */
    nodeTypes?: RAGNodeType[];

    /** Include only specific relationship types */
    relationshipTypes?: RAGRelationshipType[];

    /** Time range filter */
    timeRange?: {
        start: Date | string;
        end: Date | string;
    };

    /** Minimum importance threshold */
    minImportance?: number;

    /** Include only specific universes */
    universeIds?: string[];

    /** Include only specific tags */
    tags?: string[];
}

/**
 * Context assembly strategy
 */
export type RAGContextStrategy =
    | 'balanced' // Balance between detail and breadth
    | 'focused' // Deep detail on focal point and immediate connections
    | 'broad' // Wider breadth with less detail
    | 'temporal' // Focus on temporal connections and timelines
    | 'character_centric' // Focus on character relationships and interactions
    | 'plot_centric'; // Focus on plot development and story structure

/**
 * Assembled context result
 */
export interface RAGContextResult {
    /** Focal node with full detail */
    focalNode: RAGNode;

    /** Context layers with decreasing detail */
    layers: RAGContextLayer[];

    /** Total token count used */
    tokenCount: number;

    /** Assembly metadata */
    metadata: RAGContextMetadata;
}

/**
 * Context layer with nodes at specific distance from focal point
 */
export interface RAGContextLayer {
    /** Distance from focal point (0 = focal, 1 = direct, 2+ = indirect) */
    distance: number;

    /** Nodes in this layer with appropriate detail level */
    nodes: RAGContextNode[];

    /** Relationships within and to this layer */
    relationships: RAGRelationship[];

    /** Summary of this layer */
    summary?: string;
}

/**
 * Node in context with appropriate detail level
 */
export interface RAGContextNode {
    /** Base node information */
    node: RAGNode;

    /** Detail level used for this context */
    detailLevel: 'full' | 'detailed' | 'medium' | 'brief';

    /** Relevance score for this context */
    relevanceScore: number;

    /** Path from focal node */
    pathFromFocal: string[];
}

/**
 * Metadata about context assembly
 */
export interface RAGContextMetadata {
    /** When context was assembled */
    assembledAt: Date;

    /** Strategy used */
    strategy: RAGContextStrategy;

    /** Filters applied */
    filters?: RAGContextFilters;

    /** Performance metrics */
    performance: {
        assemblyTime: number; // milliseconds
        nodesProcessed: number;
        relationshipsProcessed: number;
        cacheHitRate?: number;
    };

    /** Warnings or limitations */
    warnings?: string[];
}

/**
 * Search request for RAG system
 */
export interface RAGSearchRequest {
    /** Search query text */
    query: string;

    /** Search mode */
    mode: RAGSearchMode;

    /** Filters */
    filters?: RAGContextFilters;

    /** Maximum results */
    limit?: number;

    /** User making the request */
    userId: string;

    /** Universe context */
    universeId?: string;
}

/**
 * Search modes
 */
export type RAGSearchMode =
    | 'semantic' // Vector similarity search
    | 'text' // Full-text search
    | 'hybrid' // Combination of semantic and text
    | 'temporal' // Time-based search
    | 'relationship' // Search by relationship patterns
    | 'plugin'; // Plugin-specific search

/**
 * Search result
 */
export interface RAGSearchResult {
    /** Matching nodes */
    nodes: RAGSearchNode[];

    /** Total count (may be larger than returned nodes) */
    totalCount: number;

    /** Search metadata */
    metadata: RAGSearchMetadata;
}

/**
 * Node in search results
 */
export interface RAGSearchNode {
    /** The matching node */
    node: RAGNode;

    /** Relevance score (0-1) */
    score: number;

    /** Matching highlights */
    highlights: string[];

    /** Match reason/explanation */
    matchReason: string;
}

/**
 * Search metadata
 */
export interface RAGSearchMetadata {
    /** Search time in milliseconds */
    searchTime: number;

    /** Mode used */
    mode: RAGSearchMode;

    /** Whether results were cached */
    cached: boolean;

    /** Search suggestions */
    suggestions?: string[];
}

/**
 * Plugin integration interface for RAG system
 */
export interface RAGPluginInterface {
    /** Plugin identifier */
    pluginId: string;

    /** Custom node types this plugin contributes */
    nodeTypes: string[];

    /** Custom relationship types this plugin contributes */
    relationshipTypes: string[];

    /** Validation rules for plugin content */
    validationRules: RAGValidationRule[];

    /** Custom summarization strategies */
    summarizationStrategies?: Record<string, (content: any) => RAGNodeSummaries>;

    /** Custom context assembly rules */
    contextRules?: RAGContextRule[];

    /** Timeline schemas (stardate, BBY/ABY, etc.) */
    timelineSchemas?: RAGTimelineSchema[];

    /** Encryption strategies specific to this plugin */
    encryptionStrategies?: RAGEncryptionStrategy[];
}

/**
 * Validation rule for plugin content
 */
export interface RAGValidationRule {
    /** Field path to validate */
    field: string;

    /** Validation type */
    type: 'required' | 'format' | 'range' | 'custom';

    /** Validation parameters */
    params?: any;

    /** Error message */
    message: string;
}

/**
 * Context assembly rule for plugins
 */
export interface RAGContextRule {
    /** When this rule applies */
    condition: (node: RAGNode, context: RAGContextRequest) => boolean;

    /** How to modify context assembly */
    action: (context: RAGContextResult) => RAGContextResult;

    /** Priority of this rule */
    priority: number;
}

/**
 * Timeline schema for universe-specific time systems
 */
export interface RAGTimelineSchema {
    /** Schema identifier */
    id: string;

    /** Display name */
    name: string;

    /** How to parse dates in this system */
    parser: (input: string) => Date | null;

    /** How to format dates for display */
    formatter: (date: Date) => string;

    /** Validation for date inputs */
    validator: (input: string) => boolean;
}

/**
 * Plugin-specific encryption strategy
 */
export interface RAGEncryptionStrategy {
    /** Strategy identifier */
    id: string;

    /** When to apply this strategy */
    condition: (node: RAGNode) => boolean;

    /** Encryption level to use */
    encryptionLevel: 'basic' | 'sensitive' | 'restricted';

    /** Additional key derivation parameters */
    keyDerivation?: Record<string, any>;
}
