/**
 * RAG Node Encryption Service
 * 
 * Handles encryption and decryption of RAG nodes while preserving
 * graph structure and enabling encrypted search capabilities.
 */

import { randomUUID } from 'crypto';
import { MongoClient, Collection, Db } from 'mongodb';
import {
    EncryptedRAGNodeDocument,
    EncryptedRAGNodeCreate,
    EncryptedRAGNodeUpdate,
    EncryptedRAGNodeFilter,
    encryptedRAGNodeCollectionConfig
} from '../../schemas/encrypted-rag-node.schema.js';
import { BaseEncryptionService } from './base-encryption.service.js';
import { ContentKeyManager } from './content-key-manager.service.js';
import { CollaborativeKeyService } from './collaborative-key.service.js';
import { createHash } from 'crypto';

/**
 * RAG Node interface - simplified version for backend use
 */
export interface RAGNode {
    id: string;
    type: string;
    title: string;
    content: {
        description: string;
        attributes?: Record<string, any>;
        structured?: any;
        fullText?: string;
    };
    summaries: {
        brief: string;
        medium: string;
        detailed: string;
        autoGenerated?: boolean;
        lastUpdated?: Date;
    };
    embeddings: number[];
    metadata: {
        universeId: string;
        ownerId: string;
        sensitivity: 'public' | 'private' | 'sensitive' | 'restricted';
        tags: string[];
        sourcePlugin?: string;
        version: number;
        importance?: number;
    };
    privacy: {
        encrypted: boolean;
        encryptionLevel?: 'basic' | 'sensitive' | 'restricted';
        keyPath?: string;
        accessList?: string[];
        shareable: boolean;
    };
    temporal?: {
        startDate?: Date | string;
        endDate?: Date | string;
        universeTime?: string;
        sequence?: number;
        ongoing?: boolean;
    };
    pluginData?: Record<string, any>;
    timestamps: {
        created: Date;
        modified: Date;
        lastAccessed?: Date;
        contentHash?: string;
    };
}

/**
 * Encryption result with metadata
 */
export interface EncryptionResult {
    success: boolean;
    encryptedData?: string;
    initializationVector?: string;
    authenticationTag?: string;
    error?: string;
}

/**
 * Decryption result with metadata
 */
export interface DecryptionResult {
    success: boolean;
    decryptedData?: any;
    error?: string;
}

/**
 * Search token generation result
 */
export interface SearchTokenResult {
    encryptedTokens: string[];
    tokenHash: string;
}

/**
 * Access control result
 */
export interface AccessControlResult {
    hasAccess: boolean;
    accessLevel?: 'read' | 'write' | 'admin';
    reason?: string;
}

/**
 * RAG Node Encryption Service
 */
export class RAGNodeEncryptionService {
    private db: Db;
    private collection: Collection<EncryptedRAGNodeDocument>;
    private baseEncryption: BaseEncryptionService;
    private contentKeyManager: ContentKeyManager;
    private collaborativeKeyService: CollaborativeKeyService;

    constructor(
        mongoClient: MongoClient,
        baseEncryption: BaseEncryptionService,
        contentKeyManager: ContentKeyManager,
        collaborativeKeyService: CollaborativeKeyService
    ) {
        this.db = mongoClient.db(encryptedRAGNodeCollectionConfig.databaseName);
        this.collection = this.db.collection<EncryptedRAGNodeDocument>(
            encryptedRAGNodeCollectionConfig.collectionName
        );
        this.baseEncryption = baseEncryption;
        this.contentKeyManager = contentKeyManager;
        this.collaborativeKeyService = collaborativeKeyService;
    }

    /**
     * Initialize the encrypted RAG node collection
     */
    async initialize(): Promise<void> {
        try {
            // Create collection if it doesn't exist
            const collections = await this.db.listCollections({
                name: encryptedRAGNodeCollectionConfig.collectionName
            }).toArray();

            if (collections.length === 0) {
                await this.db.createCollection(
                    encryptedRAGNodeCollectionConfig.collectionName,
                    { validator: encryptedRAGNodeCollectionConfig.schema }
                );
            }

            // Create indexes - create them individually to avoid type issues
            for (const indexSpec of encryptedRAGNodeCollectionConfig.indexes) {
                try {
                    await this.collection.createIndex(indexSpec, encryptedRAGNodeCollectionConfig.indexOptions);
                } catch (error) {
                    console.warn('Failed to create index:', indexSpec, error);
                }
            }

            console.log('Encrypted RAG node collection initialized successfully');
        } catch (error) {
            console.error('Failed to initialize encrypted RAG node collection:', error);
            throw error;
        }
    }

    /**
     * Encrypt a RAG node and store it
     */
    async encryptNode(
        node: RAGNode,
        userId: string,
        universeId: string,
        collaboratorIds: string[] = []
    ): Promise<{ success: boolean; nodeId?: string; error?: string }> {
        try {
            // Check if user has access to universe
            const accessCheck = await this.checkAccess(userId, universeId);
            if (!accessCheck.hasAccess || accessCheck.accessLevel === 'read') {
                return { success: false, error: 'Insufficient permissions to encrypt nodes' };
            }

            // Get or create content key for universe
            const contentKeyResult = await this.contentKeyManager.getOrCreateContentKeyWithMetadata(
                universeId,
                userId,
                'dummy-private-key', // TODO: Get user's actual private key
                [...collaboratorIds, userId]
            );

            if (!contentKeyResult) {
                return { success: false, error: 'Failed to obtain content key' };
            }

            const { key: contentKey, id: contentKeyId } = contentKeyResult;

            // Generate derived key for this specific node
            const keyDerivationPath = `${universeId}/${node.type}/${node.id}`;
            const derivedKey = await this.baseEncryption.deriveKey(
                contentKey,
                keyDerivationPath,
                32 // 256 bits
            );

            // Encrypt each field separately
            const encryptedTitle = await this.encryptField(derivedKey, node.title);
            const encryptedContent = await this.encryptField(derivedKey, node.content);
            const encryptedSummaries = await this.encryptField(derivedKey, node.summaries);
            const encryptedEmbeddings = await this.encryptField(derivedKey, node.embeddings);
            const encryptedMetadata = await this.encryptField(derivedKey, node.metadata);
            const encryptedTemporal = node.temporal ?
                await this.encryptField(derivedKey, node.temporal) : undefined;
            const encryptedPluginData = node.pluginData ?
                await this.encryptField(derivedKey, node.pluginData) : undefined;

            // Check if any encryption failed
            const encryptionResults = [
                encryptedTitle, encryptedContent, encryptedSummaries,
                encryptedEmbeddings, encryptedMetadata
            ];

            if (encryptedTemporal) encryptionResults.push(encryptedTemporal);
            if (encryptedPluginData) encryptionResults.push(encryptedPluginData);

            const failedEncryption = encryptionResults.find(result => !result.success);
            if (failedEncryption) {
                return { success: false, error: `Encryption failed: ${failedEncryption.error}` };
            }

            // Generate search tokens
            const searchTokens = await this.generateSearchTokens(derivedKey, node);

            // Create encrypted node document
            const now = new Date();
            const encryptedNode: EncryptedRAGNodeDocument = {
                nodeId: node.id,
                universeId,
                contentKeyId: contentKeyId,
                type: node.type,
                encryptedTitle: encryptedTitle.encryptedData!,
                encryptedContent: encryptedContent.encryptedData!,
                encryptedSummaries: encryptedSummaries.encryptedData!,
                encryptedEmbeddings: encryptedEmbeddings.encryptedData!,
                encryptedMetadata: encryptedMetadata.encryptedData!,
                encryptedTemporal: encryptedTemporal?.encryptedData,
                encryptedPluginData: encryptedPluginData?.encryptedData,
                encryptionMeta: {
                    algorithm: 'AES-256-GCM',
                    keyDerivationPath,
                    initializationVector: encryptedContent.initializationVector!,
                    authenticationTag: encryptedContent.authenticationTag!,
                    encryptedAt: new Date()
                },
                relationshipMeta: {
                    incomingConnectionCount: 0,
                    outgoingConnectionCount: 0,
                    relationshipTypes: [],
                    lastGraphUpdate: new Date()
                },
                accessMeta: {
                    ownerId: userId,
                    sensitivity: node.metadata.sensitivity,
                    collaboratorIds: [...collaboratorIds, userId],
                    isShared: collaboratorIds.length > 0,
                    accessLevel: 'admin'
                },
                timestamps: {
                    created: now,
                    modified: now,
                    contentHash: this.generateContentHash(encryptedContent.encryptedData!)
                },
                searchMeta: {
                    encryptedTokens: searchTokens.encryptedTokens,
                    tokenHash: searchTokens.tokenHash,
                    lastIndexed: new Date()
                }
            };

            // Store encrypted node
            await this.collection.insertOne(encryptedNode as EncryptedRAGNodeDocument);

            return { success: true, nodeId: node.id };
        } catch (error) {
            console.error('Failed to encrypt RAG node:', error);
            return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
        }
    }

    /**
     * Decrypt a RAG node
     */
    async decryptNode(
        nodeId: string,
        userId: string
    ): Promise<{ success: boolean; node?: RAGNode; error?: string }> {
        try {
            // Get encrypted node
            const encryptedNode = await this.collection.findOne({ nodeId });
            if (!encryptedNode) {
                return { success: false, error: 'Node not found' };
            }

            // Check access
            const accessCheck = await this.checkNodeAccess(userId, encryptedNode);
            if (!accessCheck.hasAccess) {
                return { success: false, error: accessCheck.reason || 'Access denied' };
            }

            // Get content key (simplified - in production would need user's private key)
            const contentKey = await this.contentKeyManager.getContentKey(
                encryptedNode.contentKeyId,
                userId,
                'dummy-private-key' // TODO: Get user's actual private key
            );

            if (!contentKey) {
                return { success: false, error: 'Content key not accessible' };
            }

            // Derive key for this node
            const derivedKey = await this.baseEncryption.deriveKey(
                contentKey,
                encryptedNode.encryptionMeta.keyDerivationPath,
                32
            );

            // Decrypt each field
            const decryptedTitle = await this.decryptField(derivedKey, encryptedNode.encryptedTitle);
            const decryptedContent = await this.decryptField(derivedKey, encryptedNode.encryptedContent);
            const decryptedSummaries = await this.decryptField(derivedKey, encryptedNode.encryptedSummaries);
            const decryptedEmbeddings = await this.decryptField(derivedKey, encryptedNode.encryptedEmbeddings);
            const decryptedMetadata = await this.decryptField(derivedKey, encryptedNode.encryptedMetadata);

            const decryptedTemporal = encryptedNode.encryptedTemporal ?
                await this.decryptField(derivedKey, encryptedNode.encryptedTemporal) : undefined;
            const decryptedPluginData = encryptedNode.encryptedPluginData ?
                await this.decryptField(derivedKey, encryptedNode.encryptedPluginData) : undefined;

            // Check if any decryption failed
            const decryptionResults = [
                decryptedTitle, decryptedContent, decryptedSummaries,
                decryptedEmbeddings, decryptedMetadata
            ];

            if (decryptedTemporal) decryptionResults.push(decryptedTemporal);
            if (decryptedPluginData) decryptionResults.push(decryptedPluginData);

            const failedDecryption = decryptionResults.find(result => !result.success);
            if (failedDecryption) {
                return { success: false, error: `Decryption failed: ${failedDecryption.error}` };
            }

            // Reconstruct RAG node
            const ragNode: RAGNode = {
                id: encryptedNode.nodeId,
                type: encryptedNode.type as any,
                title: decryptedTitle.decryptedData,
                content: decryptedContent.decryptedData,
                summaries: decryptedSummaries.decryptedData,
                embeddings: decryptedEmbeddings.decryptedData,
                metadata: decryptedMetadata.decryptedData,
                privacy: {
                    encrypted: true,
                    encryptionLevel: encryptedNode.accessMeta.sensitivity === 'restricted' ? 'restricted' : 'basic',
                    keyPath: encryptedNode.encryptionMeta.keyDerivationPath,
                    accessList: encryptedNode.accessMeta.collaboratorIds,
                    shareable: encryptedNode.accessMeta.isShared
                },
                temporal: decryptedTemporal?.decryptedData,
                pluginData: decryptedPluginData?.decryptedData,
                timestamps: {
                    created: encryptedNode.timestamps.created,
                    modified: encryptedNode.timestamps.modified,
                    lastAccessed: encryptedNode.timestamps.lastAccessed,
                    contentHash: encryptedNode.timestamps.contentHash
                }
            };

            // Update last accessed timestamp
            await this.collection.updateOne(
                { nodeId },
                { $set: { 'timestamps.lastAccessed': new Date() } }
            );

            return { success: true, node: ragNode };
        } catch (error) {
            console.error('Failed to decrypt RAG node:', error);
            return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
        }
    }

    /**
     * Get accessible nodes for a user (encrypted search)
     */
    async getAccessibleNodes(
        userId: string,
        universeId?: string,
        nodeType?: string,
        limit: number = 50
    ): Promise<{ nodes: EncryptedRAGNodeDocument[]; hasMore: boolean }> {
        try {
            // Build filter
            const filter: EncryptedRAGNodeFilter = {
                $or: [
                    { 'accessMeta.ownerId': userId },
                    { 'accessMeta.collaboratorIds': { $in: [userId] } }
                ]
            };

            if (universeId) {
                filter.universeId = universeId;
            }

            if (nodeType) {
                filter.type = nodeType;
            }

            // Get nodes
            const nodes = await this.collection
                .find(filter)
                .sort({ 'timestamps.modified': -1 })
                .limit(limit + 1)
                .toArray();

            const hasMore = nodes.length > limit;
            if (hasMore) {
                nodes.pop(); // Remove the extra node
            }

            return { nodes, hasMore };
        } catch (error) {
            console.error('Failed to get accessible nodes:', error);
            return { nodes: [], hasMore: false };
        }
    }

    /**
     * Update an encrypted node
     */
    async updateNode(
        nodeId: string,
        userId: string,
        updates: Partial<RAGNode>
    ): Promise<{ success: boolean; error?: string }> {
        try {
            // Get existing node
            const existingNode = await this.collection.findOne({ nodeId });
            if (!existingNode) {
                return { success: false, error: 'Node not found' };
            }

            // Check access
            const accessCheck = await this.checkNodeAccess(userId, existingNode);
            if (!accessCheck.hasAccess || accessCheck.accessLevel === 'read') {
                return { success: false, error: 'Insufficient permissions to update node' };
            }

            // Get content key (simplified)
            const contentKey = await this.contentKeyManager.getContentKey(
                existingNode.contentKeyId,
                userId,
                'dummy-private-key' // TODO: Get user's actual private key
            );

            if (!contentKey) {
                return { success: false, error: 'Content key not accessible' };
            }

            // Derive key for this node
            const derivedKey = await this.baseEncryption.deriveKey(
                contentKey,
                existingNode.encryptionMeta.keyDerivationPath,
                32
            );

            // Encrypt updated fields
            const encryptedUpdates: EncryptedRAGNodeUpdate = {};

            if (updates.title) {
                const encrypted = await this.encryptField(derivedKey, updates.title);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt title: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedTitle = encrypted.encryptedData!;
            }

            if (updates.content) {
                const encrypted = await this.encryptField(derivedKey, updates.content);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt content: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedContent = encrypted.encryptedData!;
            }

            if (updates.summaries) {
                const encrypted = await this.encryptField(derivedKey, updates.summaries);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt summaries: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedSummaries = encrypted.encryptedData!;
            }

            if (updates.embeddings) {
                const encrypted = await this.encryptField(derivedKey, updates.embeddings);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt embeddings: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedEmbeddings = encrypted.encryptedData!;
            }

            if (updates.metadata) {
                const encrypted = await this.encryptField(derivedKey, updates.metadata);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt metadata: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedMetadata = encrypted.encryptedData!;
            }

            if (updates.temporal) {
                const encrypted = await this.encryptField(derivedKey, updates.temporal);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt temporal: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedTemporal = encrypted.encryptedData!;
            }

            if (updates.pluginData) {
                const encrypted = await this.encryptField(derivedKey, updates.pluginData);
                if (!encrypted.success) {
                    return { success: false, error: `Failed to encrypt plugin data: ${encrypted.error}` };
                }
                encryptedUpdates.encryptedPluginData = encrypted.encryptedData!;
            }

            // Update timestamps
            const now = new Date();
            const updateDoc: any = {
                ...encryptedUpdates,
                'timestamps.modified': now
            };

            // Update content hash if content was changed
            if (encryptedUpdates.encryptedContent) {
                updateDoc['timestamps.contentHash'] = this.generateContentHash(encryptedUpdates.encryptedContent);
            }

            // Update search tokens if content changed
            if (updates.title || updates.content || updates.summaries) {
                // We need to get the full decrypted node to regenerate search tokens
                const decryptResult = await this.decryptNode(nodeId, userId);
                if (decryptResult.success && decryptResult.node) {
                    const updatedNode = { ...decryptResult.node, ...updates };
                    const searchTokens = await this.generateSearchTokens(derivedKey, updatedNode);
                    updateDoc['searchMeta.encryptedTokens'] = searchTokens.encryptedTokens;
                    updateDoc['searchMeta.tokenHash'] = searchTokens.tokenHash;
                    updateDoc['searchMeta.lastIndexed'] = now;
                }
            }

            // Perform update
            await this.collection.updateOne(
                { nodeId },
                { $set: updateDoc }
            );

            return { success: true };
        } catch (error) {
            console.error('Failed to update encrypted node:', error);
            return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
        }
    }

    /**
     * Delete an encrypted node
     */
    async deleteNode(
        nodeId: string,
        userId: string
    ): Promise<{ success: boolean; error?: string }> {
        try {
            // Get existing node
            const existingNode = await this.collection.findOne({ nodeId });
            if (!existingNode) {
                return { success: false, error: 'Node not found' };
            }

            // Check access - only owner or admin can delete
            const accessCheck = await this.checkNodeAccess(userId, existingNode);
            if (!accessCheck.hasAccess ||
                (accessCheck.accessLevel !== 'admin' && existingNode.accessMeta.ownerId !== userId)) {
                return { success: false, error: 'Insufficient permissions to delete node' };
            }

            // Delete node
            await this.collection.deleteOne({ nodeId });

            return { success: true };
        } catch (error) {
            console.error('Failed to delete encrypted node:', error);
            return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
        }
    }

    /**
     * Add collaborator to node
     */
    async addCollaborator(
        nodeId: string,
        userId: string,
        collaboratorId: string,
        accessLevel: 'read' | 'write' | 'admin' = 'read'
    ): Promise<{ success: boolean; error?: string }> {
        try {
            // Get existing node
            const existingNode = await this.collection.findOne({ nodeId });
            if (!existingNode) {
                return { success: false, error: 'Node not found' };
            }

            // Check access - only owner or admin can add collaborators
            const accessCheck = await this.checkNodeAccess(userId, existingNode);
            if (!accessCheck.hasAccess || accessCheck.accessLevel === 'read') {
                return { success: false, error: 'Insufficient permissions to add collaborators' };
            }

            // Check if collaborator already has access
            if (existingNode.accessMeta.collaboratorIds.includes(collaboratorId)) {
                return { success: false, error: 'User already has access to this node' };
            }

            // Add collaborator to content key
            const keyResult = await this.contentKeyManager.addCollaborator(
                existingNode.contentKeyId,
                { userId: collaboratorId, publicKey: 'dummy-public-key' }, // TODO: Get user's actual public key
                userId,
                'dummy-private-key' // TODO: Get user's actual private key
            );

            if (!keyResult.success) {
                return { success: false, error: `Failed to add collaborator to content key: ${keyResult.error}` };
            }

            // Update node access metadata
            await this.collection.updateOne(
                { nodeId },
                {
                    $push: { 'accessMeta.collaboratorIds': collaboratorId },
                    $set: {
                        'accessMeta.isShared': true,
                        'accessMeta.accessLevel': accessLevel,
                        'timestamps.modified': new Date()
                    }
                }
            );

            return { success: true };
        } catch (error) {
            console.error('Failed to add collaborator:', error);
            return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
        }
    }

    /**
     * Remove collaborator from node
     */
    async removeCollaborator(
        nodeId: string,
        userId: string,
        collaboratorId: string
    ): Promise<{ success: boolean; error?: string }> {
        try {
            // Get existing node
            const existingNode = await this.collection.findOne({ nodeId });
            if (!existingNode) {
                return { success: false, error: 'Node not found' };
            }

            // Check access - only owner or admin can remove collaborators
            const accessCheck = await this.checkNodeAccess(userId, existingNode);
            if (!accessCheck.hasAccess ||
                (accessCheck.accessLevel !== 'admin' && existingNode.accessMeta.ownerId !== userId)) {
                return { success: false, error: 'Insufficient permissions to remove collaborators' };
            }

            // Remove collaborator from content key
            const keyResult = await this.contentKeyManager.removeCollaborator(
                existingNode.contentKeyId,
                collaboratorId,
                userId
            );

            if (!keyResult.success) {
                return { success: false, error: `Failed to remove collaborator from content key: ${keyResult.error}` };
            }

            // Update node access metadata
            const updatedCollaborators = existingNode.accessMeta.collaboratorIds.filter(id => id !== collaboratorId);

            await this.collection.updateOne(
                { nodeId },
                {
                    $set: {
                        'accessMeta.collaboratorIds': updatedCollaborators,
                        'accessMeta.isShared': updatedCollaborators.length > 1,
                        'timestamps.modified': new Date()
                    }
                }
            );

            return { success: true };
        } catch (error) {
            console.error('Failed to remove collaborator:', error);
            return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
        }
    }

    /**
     * Perform encrypted search
     */
    async searchEncrypted(
        userId: string,
        searchTerms: string[],
        universeId?: string,
        nodeType?: string,
        limit: number = 20
    ): Promise<{ nodes: EncryptedRAGNodeDocument[]; hasMore: boolean }> {
        try {
            // Build base filter for access control
            const filter: EncryptedRAGNodeFilter = {
                $or: [
                    { 'accessMeta.ownerId': userId },
                    { 'accessMeta.collaboratorIds': { $in: [userId] } }
                ]
            };

            if (universeId) {
                filter.universeId = universeId;
            }

            if (nodeType) {
                filter.type = nodeType;
            }

            // Get accessible nodes with search metadata
            const accessibleNodes = await this.collection
                .find(filter)
                .toArray();

            // Filter by search terms (basic implementation)
            // In production, this would use proper encrypted search techniques
            const searchResults: EncryptedRAGNodeDocument[] = [];

            for (const node of accessibleNodes) {
                if (searchResults.length >= limit) break;

                // Get content key and decrypt for search
                const contentKey = await this.contentKeyManager.getContentKey(
                    node.contentKeyId,
                    userId,
                    'dummy-private-key' // TODO: Get user's actual private key
                );

                if (contentKey) {
                    // Simple search token matching
                    const tokenHash = this.generateSearchHash(searchTerms);

                    // For now, include all accessible nodes
                    // TODO: Implement proper encrypted search token matching
                    searchResults.push(node);
                }
            }

            const hasMore = searchResults.length === limit && accessibleNodes.length > limit;

            return { nodes: searchResults.slice(0, limit), hasMore };
        } catch (error) {
            console.error('Failed to perform encrypted search:', error);
            return { nodes: [], hasMore: false };
        }
    }

    /**
     * Private helper methods
     */
    private async encryptField(key: Buffer, data: any): Promise<EncryptionResult> {
        try {
            const serialized = JSON.stringify(data);
            const result = await this.baseEncryption.encrypt(serialized, key);
            return {
                success: true,
                encryptedData: Buffer.from(JSON.stringify(result)).toString('base64'),
                initializationVector: result.iv,
                authenticationTag: result.authTag || ''
            };
        } catch (error) {
            return {
                success: false,
                error: error instanceof Error ? error.message : 'Unknown encryption error'
            };
        }
    }

    private async decryptField(key: Buffer, encryptedData: string): Promise<DecryptionResult> {
        try {
            const decrypted = await this.baseEncryption.decrypt(encryptedData, key);
            return {
                success: true,
                decryptedData: JSON.parse(decrypted)
            };
        } catch (error) {
            return {
                success: false,
                error: error instanceof Error ? error.message : 'Unknown decryption error'
            };
        }
    }

    private async generateSearchTokens(key: Buffer, node: RAGNode): Promise<SearchTokenResult> {
        try {
            // Extract searchable text
            const searchableText = [
                node.title,
                node.content.description,
                node.content.fullText || '',
                node.summaries.brief,
                node.summaries.medium,
                node.summaries.detailed,
                ...node.metadata.tags
            ].join(' ').toLowerCase();

            // Generate search tokens (simple word extraction)
            const tokens = searchableText
                .split(/\s+/)
                .filter(token => token.length > 2)
                .slice(0, 100); // Limit tokens

            // Encrypt tokens
            const encryptedTokens: string[] = [];
            for (const token of tokens) {
                const encrypted = await this.baseEncryption.encrypt(token, key);
                encryptedTokens.push(encrypted.data);
            }

            const tokenHash = this.generateSearchHash(tokens);

            return { encryptedTokens, tokenHash };
        } catch (error) {
            console.error('Failed to generate search tokens:', error);
            return { encryptedTokens: [], tokenHash: '' };
        }
    }

    private generateSearchHash(tokens: string[]): string {
        return createHash('sha256')
            .update(tokens.sort().join('|'))
            .digest('hex');
    }

    private generateContentHash(content: string): string {
        return createHash('sha256')
            .update(content)
            .digest('hex');
    }

    private async checkAccess(userId: string, universeId: string): Promise<AccessControlResult> {
        // This would integrate with the main access control system
        // For now, assume basic access
        return { hasAccess: true, accessLevel: 'admin' };
    }

    private async checkNodeAccess(
        userId: string,
        node: EncryptedRAGNodeDocument
    ): Promise<AccessControlResult> {
        // Check if user is owner
        if (node.accessMeta.ownerId === userId) {
            return { hasAccess: true, accessLevel: 'admin' };
        }

        // Check if user is collaborator
        if (node.accessMeta.collaboratorIds.includes(userId)) {
            return { hasAccess: true, accessLevel: node.accessMeta.accessLevel };
        }

        // Check if content is public
        if (node.accessMeta.sensitivity === 'public') {
            return { hasAccess: true, accessLevel: 'read' };
        }

        return { hasAccess: false, reason: 'User not authorized to access this node' };
    }
}
